project_name: FileModTracker
version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

release:
  github:
    owner: tejiriaustin
    name: savannah-assessment

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
